/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(frame_sorter_cpp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(411bad03e53d0de92a3d280c0c712643)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/frame_sorter_cpp.h>
// pydoc.h is automatically generated in the build directory
#include <frame_sorter_cpp_pydoc.h>

void bind_frame_sorter_cpp(py::module& m)
{

    using frame_sorter_cpp    = ::gr::iridium::frame_sorter_cpp;


    py::class_<frame_sorter_cpp, gr::block, gr::basic_block,
        std::shared_ptr<frame_sorter_cpp>>(m, "frame_sorter_cpp", D(frame_sorter_cpp))

        .def(py::init(&frame_sorter_cpp::make),
           D(frame_sorter_cpp,make)
        )
        



        ;




}








