/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(iridium_qpsk_demod_cpp.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9126147ce941c38d40d66a1b92cccd69)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <iridium/iridium_qpsk_demod_cpp.h>
// pydoc.h is automatically generated in the build directory
#include <iridium_qpsk_demod_cpp_pydoc.h>

void bind_iridium_qpsk_demod_cpp(py::module& m)
{

    using iridium_qpsk_demod_cpp    = ::gr::iridium::iridium_qpsk_demod_cpp;


    py::class_<iridium_qpsk_demod_cpp, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<iridium_qpsk_demod_cpp>>(m, "iridium_qpsk_demod_cpp", D(iridium_qpsk_demod_cpp))

        .def(py::init(&iridium_qpsk_demod_cpp::make),
           D(iridium_qpsk_demod_cpp,make)
        )
        




        
        .def("get_n_handled_bursts",&iridium_qpsk_demod_cpp::get_n_handled_bursts,       
            D(iridium_qpsk_demod_cpp,get_n_handled_bursts)
        )


        
        .def("get_n_access_ok_bursts",&iridium_qpsk_demod_cpp::get_n_access_ok_bursts,       
            D(iridium_qpsk_demod_cpp,get_n_access_ok_bursts)
        )

        ;




}








